name: burrito-nightly

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  nightly:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/burrito-release.yml
    with:
      nightly: true
